### ISSUE TITLE
在一个页面使用多个图表会覆盖

### ISSUE THREAD

**Issue by tangqq** [Cecilxx/echarts-taro3-react#1]
请问一下我在同一个页面里面 使用的多个图表。我看到代码里是用的select(".ec-chart")查找元素，是不是不支持同一页面使用多个图表？

**Comment by Cecilxx** [comment]
@tangqq 不好意思才看到，之前确实没有，最新版本（1.0.7）已经加上了，可参考`pages/more`使用示例

**Comment by tangqq** [comment]
非常感谢，自己稍微修改下一家弄好了。
