### ISSUE TITLE
如何监听echarts 点击/触摸事件

### ISSUE THREAD

**Issue by wuhao930406** [Cecilxx/echarts-taro3-react#11]
this.lineChart.on("click",(params)=>{
            console.log(params)
   })

  .on is not a function

**Comment by a992681784** [comment]
遇到同样的问题了 有解决办法了吗

**Comment by wuhao930406** [comment]
> 遇到同样的问题了 有解决办法了吗

没有 暂时使用tooltip方式替代了一下

**Comment by Cecilxx** [comment]
不好意思，最近生了场大病，更新的有点慢了，更新至1.0.13版本，即可增加绑定事件
![image](https://user-images.githubusercontent.com/20623617/115355610-68a69200-a1ed-11eb-8f99-7e74f90f5c93.png)

使用例子在pages/bar下面
