### ISSUE TITLE
可以做一个绑定事件的示例吗 我实在找不到办法给图表绑定事件

### ISSUE THREAD

**Issue by SileceAgle** [Cecilxx/echarts-taro3-react#17]

**Comment by a992681784** [comment]
我也是项目中有一个雷达图需要绑定点击事件 实在找不到办法。希望被看到

**Comment by Cecilxx** [comment]
不好意识最近生了场大病，更新的有点慢了，更新至1.0.13版本，即可增加绑定事件
![image](https://user-images.githubusercontent.com/20623617/115355610-68a69200-a1ed-11eb-8f99-7e74f90f5c93.png)

使用例子在pages/bar下面

**Comment by SileceAgle** [comment]
> 那个点击事件在移动端触发会有异常 看着是不止触发了一次的样子

**Comment by Cecilxx** [comment]
> > 那个点击事件在移动端触发会有异常 看着是不止触发了一次的样子

我在预览模式下尝试了一下只会触发一次（IOS），可以提供下机型和代码吗

**Comment by SileceAgle** [comment]
`import Taro from '@tarojs/taro';
import React, { Component } from 'react';
import { View, Canvas } from '@tarojs/components';
import { EChart } from 'echarts-taro3-react';
import { dimensionLevelTransformName } from '@/assets/js/statusCode';
import { PRODUCT_DETAIL_CHECK } from '@/config/index';
import style from './LastSkinTestRadar.module.less';

class Pie extends Component {
  static defaultProps = {
    data: {
      data: [{}],
      indicator: [{}, {}, {}, {}, {}, {}],
    },
    photographDetail: {},
  };

  constructor(props) {
    super(props);
    this.state = {
      isOpenModal: false,
      activeList: [],
      noneList: [],
      modalTitle: '痘痘',
      modalData: {},
    };
  }

  componentDidMount() {
    // 因为小程序不支持js的Image 所以用canvas创建一个img元素传给小程序
    this.createImg = setTimeout(() => {
      const query = Taro.createSelectorQuery();
      query
        .select('#myCanvas')
        .fields({
          node: true,
          size: true,
        })
        .exec((res) => {
          const cvs = res[0].node;
          cvs.width = 12; // 宽高
          cvs.height = 12;
          const img = cvs.createImage();
          img.onload = function () {
            const ctx = cvs.getContext('2d');
            ctx.drawImage(img, 0, 0, 12, 12);
          };
          img.src = PRODUCT_DETAIL_CHECK;
          this.myImage = img;
          this.refresh();
        });
    }, 500);
  }

  componentWillUnmount() {
    clearTimeout(this.createImg);
  }

  // 处理弹窗数据
  processingPhotographDetail = () => {
    let { photographDetail } = this.props;
    let {
      acneOverall,
      pigmentationOverall,
      wrinkleOverall,
      oilPhotograph,
      moisturePhotograph,
      sensitiveDescribe,
    } = photographDetail;
    let checkLevel = ['', '无', '轻', '中', '重'];
    const dataProcessing = {
      erythema: (level) => {
        return '红斑·' + checkLevel[level];
      },
      nodule: (level) => {
        return '结节囊肿·' + checkLevel[level];
      },
      papules: (level) => {
        return '炎症丘疹·' + checkLevel[level];
      },
      pimple: (level) => {
        return '粉刺·' + checkLevel[level];
      },
      pustule: (level) => {
        return '脓包·' + checkLevel[level];
      },
      scar: (level) => {
        return '凹陷性斑痕·' + checkLevel[level];
      },
      chloasma: (level) => {
        return '黄褐斑·' + checkLevel[level];
      },
      freckles: (level) => {
        return '雀斑·' + checkLevel[level];
      },
      hidingSpot: (level) => {
        return '隐藏斑·' + checkLevel[level];
      },
      mole: (level) => {
        return '黑痣·' + checkLevel[level];
      },
      crowfeet: (level) => {
        return '鱼尾纹·' + checkLevel[level];
      },
      foreheadWrinkle: (level) => {
        return '抬头纹·' + checkLevel[level];
      },
      glabella: (level) => {
        return '眉间纹·' + checkLevel[level];
      },
      nasolabialFolds: (level) => {
        return '法令纹·' + checkLevel[level];
      },
      risoriusMuscle: (level) => {
        return '笑肌断层·' + checkLevel[level];
      },
      tearTrough: (level) => {
        return '泪沟·' + checkLevel[level];
      },
      moisturePhotograph: (level) => {
        return dimensionLevelTransformName(3, level);
      },
      oilPhotograph: (level) => {
        return dimensionLevelTransformName(4, level);
      },
      sensitiveDescribe: (level) => {
        return dimensionLevelTransformName(9, level);
      },
    };
    const dataProcessingFun = (type, level) => {
      if (typeof dataProcessing[type] === 'function') {
        return dataProcessing[type](level);
      }
    };
    let acneOverallActive = [];
    let acneOverallNone = [];
    for (let i in acneOverall) {
      if (acneOverall[i].level > 1) {
        acneOverallActive.push(dataProcessingFun(i, acneOverall[i].level));
      } else {
        acneOverallNone.push(dataProcessingFun(i, acneOverall[i].level));
      }
    }
    let pigmentationOverallActive = [];
    let pigmentationOverallNone = [];
    for (let i in pigmentationOverall) {
      if (pigmentationOverall[i].level > 1) {
        pigmentationOverallActive.push(dataProcessingFun(i, pigmentationOverall[i].level));
      } else {
        pigmentationOverallNone.push(dataProcessingFun(i, pigmentationOverall[i].level));
      }
    }
    let wrinkleOverallActive = [];
    let wrinkleOverallNone = [];
    for (let i in wrinkleOverall) {
      if (wrinkleOverall[i].level > 1) {
        wrinkleOverallActive.push(dataProcessingFun(i, wrinkleOverall[i].level));
      } else {
        wrinkleOverallNone.push(dataProcessingFun(i, wrinkleOverall[i].level));
      }
    }
    let data = {
      acneOverall: {
        modalNoneContent: acneOverallNone,
        modalActiveContent: acneOverallActive,
      },
      wrinkleOverall: {
        modalActiveContent: wrinkleOverallActive,
        modalNoneContent: wrinkleOverallNone,
      },
      pigmentationOverall: {
        modalNoneContent: pigmentationOverallNone,
        modalActiveContent: pigmentationOverallActive,
      },
      moisturePhotograph: {
        modalActiveContent: [dataProcessingFun('moisturePhotograph', moisturePhotograph.level)],
        modalNoneContent: [''],
      },
      oilPhotograph: {
        modalActiveContent: [dataProcessingFun('oilPhotograph', oilPhotograph.level)],
        modalNoneContent: [''],
      },
      sensitiveDescribe: {
        modalActiveContent: [dataProcessingFun('sensitiveDescribe', sensitiveDescribe[0].level)],
        modalNoneContent: [''],
      },
    };
    this.setState({
      modalData: data,
    });
  };

  refresh() {
    const { data } = this.props;
    var option = {
      tooltip: {},
      radar: [
        {
          shape: 'circle',
          center: ['50%', '50%'], //位置
          radius: '61%', //半径
          startAngle: 0,
          splitNumber: 4,
          triggerEvent: true,
          name: {
            show: true, // 是否显示label
            formatter: function (params) {
              let arr = params.split('·');
              let type =
                arr[0] === '色斑'
                  ? 8
                  : arr[0] === '油分'
                  ? 4
                  : arr[0] === '水分'
                  ? 3
                  : arr[0] === '痘痘'
                  ? 10
                  : arr[0] === '敏感'
                  ? 9
                  : arr[0] === '细纹'
                  ? 11
                  : '';
              if (arr[1] > 1) {
                return '{color0|' + arr[0] + '·' + dimensionLevelTransformName(type, arr[1]) + '}';
              } else {
                return (
                  '{color1|} {color2|' +
                  arr[0] +
                  '·' +
                  dimensionLevelTransformName(type, arr[1]) +
                  '}'
                );
              }
            },
            rich: {
              color0: { color: '#FFFFFF' },
              color1: {
                backgroundColor: {
                  image: this.myImage, // img的实例对象
                  width: 12,
                  height: 12,
                },
              },
              color2: {
                color: '#A7AAB4',
              },
            },
          },
          nameGap: '6',
          indicator: data.indicator,
          splitArea: {
            areaStyle: {
              color: 'transparent',
            },
          },
          splitLine: {
            lineStyle: {
              type: 'dashed',
              color: 'rgba(255, 255, 255, 0.3)',
              width: 1,
            },
          },
          axisLine: {
            lineStyle: {
              color: 'rgba(255, 255, 255, 0.3)',
              width: 1,
            },
          },
        },
        {
          // 为了显示最外圈的白色框
          indicator: [{}],
          shape: 'circle',
          center: ['50%', '50%'], //位置
          radius: '61%', //半径
          splitNumber: 50, // 将图表的线分成50份 然后全部设置透明 只显示最外面那一份 就出来一个圆
          splitArea: {
            areaStyle: {
              show: true,
              color: [
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(0,0,0,0)',
                'rgba(167, 170, 180, 1)',
              ],
            },
          },
          axisLine: {
            lineStyle: {
              color: 'transparent',
            },
          },
          splitLine: {
            lineStyle: {
              type: 'solid',
              color: 'transparent',
            },
          },
        },
      ],
      series: [
        {
          // 用来显示的图
          label: {
            show: false,
          },
          name: '肤质问题',
          type: 'radar',
          areaStyle: {
            normal: {
              color: {
                type: 'radial',
                x: 0.5,
                y: 0.5,
                r: 0.5,
                colorStops: [
                  {
                    offset: 0,
                    color: 'rgba(78, 213, 255, 0)', // 0% 处的颜色
                  },
                  {
                    offset: 0.5,
                    color: 'rgba(78, 213, 255, 0.17)', // 50% 处的颜色
                  },
                  {
                    offset: 1,
                    color: 'rgba(78, 213, 255, 1)', // 100% 处的颜色
                  },
                ],
                global: false, // 缺省为 false
              },
            },
          },
          symbol: 'circle',
          symbolSize: 6,
          itemStyle: {
            normal: {
              color: 'rgba(37, 41, 69, 1)',
              borderColor: 'rgba(255, 255, 255, 1)',
              borderWidth: 1,
            },
          },
          lineStyle: {
            normal: {
              color: 'transparent',
              width: '0', //折线粗细
            },
          },
          tooltip: {
            show: false,
          },
          data: data.data,
        },
      ],
    };

    this.pieChart.refresh(option);
  }

  componentDidUpdate(nextProps, nextState) {
    if (JSON.stringify(nextProps.data) !== JSON.stringify(this.props.data)) {
      this.refresh();
      this.processingPhotographDetail();
    }
  }

  refPieChart = (node) => {
    this.pieChart = node;
  };

  onPage = () => {
    this.setState({
      isOpenModal: false,
    });
  };

  onClick = (params) => {
    let { modalData } = this.state;
    let { changeOpenToolTip } = this.props;
    if (params.targetType === 'axisName') {
      changeOpenToolTip(true);
      if (params.name.indexOf('细纹') > -1) {
        this.setState({
          modalTitle: '细纹',
          ...modalData.wrinkleOverall,
        });
      } else if (params.name.indexOf('油分') > -1) {
        this.setState({
          modalTitle: '油分',
          ...modalData.oilPhotograph,
        });
      } else if (params.name.indexOf('水分') > -1) {
        this.setState({
          modalTitle: '水分',
          ...modalData.moisturePhotograph,
        });
      } else if (params.name.indexOf('痘痘') > -1) {
        this.setState({
          modalTitle: '痘痘',
          ...modalData.acneOverall,
        });
      } else if (params.name.indexOf('敏感') > -1) {
        this.setState({
          modalTitle: '敏感',
          ...modalData.sensitiveDescribe,
        });
      } else if (params.name.indexOf('色斑') > -1) {
        this.setState({
          modalTitle: '色斑',
          ...modalData.pigmentationOverall,
        });
      }
    }
  };

  onMousemove = () => {
    console.log('aaa');
  };

  render() {
    let { modalTitle, modalActiveContent, modalNoneContent } = this.state;
    let { isOpenToolTip } = this.props;
    return (
      <View className='pie-chart'>
        <Canvas
          type='2d' // 2d属性不能少
          style='width: 20px; height: 20px;z-index:-1;position:relative;display:none;'
          id='myCanvas'
        />
        <EChart
          ref={this.refPieChart}
          canvasId='pie-chart'
          // onClick={this.onClick}
          // onMousemove={this.onMousemove}
          onTouchMove={this.onMousemove}
          onTouchStart={this.onMousemove}
          onTouchEnd={this.onMousemove}
        />
        <View className={style.modal} style={{ display: isOpenToolTip ? '' : 'none' }}>
          <View className={style.bit}></View>
          <View className={style.title}>{modalTitle}</View>
          <View className={style.active}>
            {modalActiveContent
              ? modalActiveContent.map((ele) => {
                  return <View>{ele}</View>;
                })
              : null}
          </View>
          <View className={style.none}>
            {modalNoneContent
              ? modalNoneContent.map((ele) => {
                  return <View>{ele}</View>;
                })
              : null}
          </View>
        </View>
      </View>
    );
  }
}

export default Pie;
`

**Comment by SileceAgle** [comment]
用的是onClick事件 因为在找方法所以那里注释掉了 
<EChart
ref={this.refPieChart}
canvasId='pie-chart'
onClick={this.onClick}
/>

**Comment by Cecilxx** [comment]
> 用的是onClick事件 因为在找方法所以那里注释掉了

我用pie饼图试了下 在ios下预览 都是可以正常触发点击事件的（一次），如果同时添加了onClick与onMousemove，这两次事件都会触发，你用的是安卓吗？

**Comment by SileceAgle** [comment]
我的目的是使用它实现一个弹窗 点击名称显示弹窗 点击名称之外关闭弹窗 猜测是点击名称时冒泡导致关闭弹窗也触发了 但是在onClick里面阻止冒泡的话导致事件直接一次都不触发了

**Comment by Cecilxx** [comment]
> 我的目的是使用它实现一个弹窗 点击名称显示弹窗 点击名称之外关闭弹窗 猜测是点击名称时冒泡导致关闭弹窗也触发了 但是在onClick里面阻止冒泡的话导致事件直接一次都不触发了

那看起来不像是onClick本身被多次触发的问题，点击名称指的是点击饼图区域吗？名称之外指的是饼图区域之外？

**Comment by SileceAgle** [comment]
名称就是那个 痘痘.无 那个名称 点击这个名称之外都可以关闭弹窗

**Comment by Cecilxx** [comment]
> 名称就是那个 痘痘.无 那个名称 点击这个名称之外都可以关闭弹窗

现在是点击关闭弹窗的时候，onClick又被触发了，然后弹窗又出现了吗？导致一直关不掉？

**Comment by SileceAgle** [comment]
点击名称的时候 导致关闭弹窗的事件触发了导致弹窗打不开

**Comment by SileceAgle** [comment]
![image(5)](https://user-images.githubusercontent.com/56986321/115650670-4bf28300-a2ef-11eb-8ac4-00c2e2523b38.png)

**Comment by a992681784** [comment]
@Cecilxx 应该是click事件冒泡引起的问题。请问下如何阻止冒泡。onClick只有一个参数params，里面的event没有stopPropagation方法。

**Comment by Cecilxx** [comment]
> @Cecilxx 应该是click事件冒泡引起的问题。请问下如何阻止冒泡。onClick只有一个参数params，里面的event没有stopPropagation方法。

确实是冒泡引起的，试一下`event.cancelBubble = true`

**Comment by SileceAgle** [comment]
> > @Cecilxx应该是clickEvent冒泡引起的问题。请问下如何阻止冒泡。onClick只有一个参数params，里面的事件没有stopPropagation方法。
> 
> 确实是冒泡引起的，试一下`event.cancelBubble = true`

这个属性加上了没有效果
