### ISSUE TITLE
Taro 3.x运行报错

### ISSUE THREAD

**Issue by santa955** [Cecilxx/echarts-taro3-react#28]
直接clone代码本地运行：

环境： Taro/cli：3.1.1

已经升级相关依赖

![210802-175751](https://user-images.githubusercontent.com/7077768/127843432-5cd3bb3d-77ff-47e2-9b65-173b7b2f02ee.png)

**Comment by hellozsh** [comment]
我也遇到同样的问题，怎么解决

**Comment by hellozsh** [comment]
> 我也遇到同样的问题，怎么解决

可以了，解决传送门 https://github.com/NervJS/taro/issues/9914
