### ISSUE TITLE
不允许多次refresh

### ISSUE THREAD

**Issue by lvshiwei** [Cecilxx/echarts-taro3-react#5]
我打开了line图表
当数据发生变化时, 再次调用 refresh 方法, 图表无刷新

`
    setTimeout(() => {
      console.log('refresh again')
      const newoption = {
        xAxis: {},
        yAxis: {},
        series: [
          {
            data: [
              [30, 320],
              [30, 300],
              [20, 250],
            ],
            type: "line",
          },
        ],
      };
      this.lineChart.refresh(newoption);
      console.log('done ');
    }, 2000);
`

**Comment by Cecilxx** [comment]
```
setTimeout(() => { console.log('refresh again') const newoption = { xAxis: {}, yAxis: {}, series: [ { data: [ [30, 320], [30, 300], [20, 250], ], type: "line", }, ], }; this.lineChart.refresh(newoption); console.log('done '); }, 2000);
```

**Comment by Cecilxx** [comment]
报错了吗？如果有的话看下是哪里报错了

**Comment by Cecilxx** [comment]
报错了吗？如果有的话，截图提供下 @lvshiwei

**Comment by jsLyLeeHi** [comment]
我也遇到这个问题了，没有报错，但是无法刷新数据

**Comment by jsLyLeeHi** [comment]
数据发生改变后使用refresh函数刷新数据图表无反应

**Comment by cham1985** [comment]
我也遇到了,垃圾插件,坑人

**Comment by cham1985** [comment]
taro 要死

**Comment by Cecilxx** [comment]
@lvshiwei @jsLyLeeHi 不是意思，最近业务上比较忙，升级到1.0.10版本即可解决。
