### ISSUE TITLE
taro 3.0 打包后，echart体积 太大超过2M

### ISSUE THREAD

**Issue by zw888** [Cecilxx/echarts-taro3-react#7]

**Comment by cham1985** [comment]
同问,求姐

**Comment by welchwsy** [comment]
https://echarts.apache.org/zh/builder.html
到官网下载压缩后的`echarts.min.js`更改名字为`echarts.js`，并替换`lib/ec-canvas`中的文件。可以只选择有用上的图表，工具集也可以不用选，版本选着4.3.0。已pie图表为例只需要310K

**Comment by Cecilxx** [comment]
@cham1985 @zw888 @welchwsy  不好意思，最近业务上有点忙，回复的有点慢，升级到1.0.10版本即可解决。
